# Site settings
title: Posh Developer
header-img: img/home-bg.png
email: inadream@gmail.com
copyright_name: icygirl
description: > # this means to ignore newlines until "baseurl:"
  A Fashionista's Journey into Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  icygirl
learn_profile: icygirl
email_username: inadream@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
